<?php
$baseUrl = $this->baseUrl();
$errorMsg = $this->errorMsg;
$successMsg = $this->successMsg;
?>

<?php
//$this->headLink()->prependStylesheet('/css/styel.css');
//echo $this->headLink();
?>

<div class="login">
    <!--div class="title-login"><h1>Forgot Password</h1></div-->
    <?php
    if (!empty($errorMsg)) {
        echo "<div id='errorMsg' style='padding-left:40px;'>";
        echo "<br/><font style='color:red;'>" . $this->escape($errorMsg) . "</font>";
        echo "</div>";
    }
    if (!empty($successMsg)) {
        echo "<div id='success' style='padding-left:25px;color:green;'>";
        echo "<br/>" . $this->escape($successMsg) . "<br/><br/>";
        echo "</div>";
    }
    ?>
    <div class="col300">
    <?php
    echo $this->form->setAction($this->url());
    ?>
    </div>
    <div class="clear"></div>
</div>
