<?php
$baseUrl = $this->baseUrl();
$errorMsg = $this->errorMsg;
$successMsg = $this->successMsg;
?>

<?php
//$this->headLink()->prependStylesheet('/css/styel.css');
//echo $this->headLink();
?>


<link href="/css/frontPanel/bootstrap.min.css" rel="stylesheet">
<link href="/css/frontPanel/style.css" rel="stylesheet">
<link href="/font/font.css" rel="stylesheet">



<style>
 #submit{
    background:url(/images/frontPanel/submit.jpg) no-repeat top left;
      
    border:none;
   // background-color: #8c8c8c;
   // border: medium none;
   // border-radius: 5px;
    color: #fff;
    cursor: pointer;
    height: 24px;
    width: 65px;
    margin: 6px auto 0;
    display: block;
    border-radius: 5px;
 }
.login-block ul {
    list-style-type: none;
     color:red;
     float:left;
}
.login{
    width: 310px !important;
}
 
</style>
<div class="login">
    <!--div class="title-login"><h1>Forgot Password</h1></div-->
    <?php
    if (!empty($errorMsg)) {
        echo "<div id='errorMsg'>";
        echo "<br/><font style='color:red;'>" . $this->escape($errorMsg) . "</font>";
        echo "</div>";
    }
    if (!empty($successMsg)) {
        echo "<div id='success' style='color:green;'>";
        echo "<br/>" . $this->escape($successMsg) . "<br/>";
        echo "</div>";  die;
    }
    ?>
    <div style="border: 40px solid #8c8c8c; border-right: none; border-left: none;" class="col300">
        <div style="padding: 20px 10px;
    width: 90%;">
            <?php
    echo $this->form->setAction($this->url());
    ?>
        </div>
    </div>
    <div class="clear"></div>
</div>
