<script src="/js/jquery-1.8.3.min.js"></script>
<script type="text/javascript" src="/js/fancybox/source/jquery.fancybox.js?v=2.1.4"></script>
<link rel="stylesheet" type="text/css" href="/js/fancybox/source/jquery.fancybox.css?v=2.1.4" media="all" />
<style>
    
    .overlay-block {
        -moz-border-bottom-colors: none;
        -moz-border-left-colors: none;
        -moz-border-right-colors: none;
        -moz-border-top-colors: none;
        background: none repeat scroll 0 0 #FFFFFF;
        border-color: #8CC63F -moz-use-text-color;
        border-image: none;
        border-style: solid none;
        border-width: 40px 0;
/*        display: table;*/
        left: 0px;;
        padding: 20px;
        position: fixed;
        top: 0px;
        width: 365px;
        height: 201px;
    }
    
   
</style>
<?php
$attInfo = $this->attInfo;

?>
<?php
    if(!empty($this->succMesg)){?>
    <script language="JavaScript" type="text/javascript">
    $(document).ready(function() {
        parent.jQuery.fancybox.close();
    });
    </script>
    <?php }
?>

<div class='contact-content'>
    
   <div class="overlay-block"><div class="errors" id="errors"></div><br/>
    <!--h3 style="padding-left:65px;">Create Application</h3><br-->
    <form name="frm_createApp" id="frm_createApp" action="/admin/product-management/savetagtwo/<?php if(!empty($attInfo)){ echo '/tid/'.$attInfo[0]['tag2_id']; }?>" method="post" enctype="multipart/form-data" onsubmit="return validation();"/>
        <p>
            <label style="font-family: verdana; font-size: 14px; color: #7F7F7F; font-weight: bold; display: block;">Product Filter2:</label>
            <input type="text" id="tiertag_title" name="tiertag_title" style="margin-top:8px;border: 1px solid #CCCCCC;border-radius: 3px 3px 3px 3px;width:100%;height: 34px;padding: 5px 0;color: rgba(0, 0, 0, 0.75);" value="<?php if(!empty($attInfo)){ echo $attInfo[0]['tag2_name']; }?>"/>
        </p>
      
        <!--p>
            <label style="font-family: verdana; font-size: 14px; color: #7F7F7F; font-weight: bold;">Image:</label>
            <input type="file" id="imgfile" name="imgfile" style="margin-left:21px;border-radius: 3px 3px 3px 3px;color: #7F7F7F;"/><br/>
            
        </p-->
        
        <p style="margin-bottom: 10px;">
             <input type="hidden" name="category" value="tag2"/>
             <input type="hidden" name="hdnattId" value="<?php if(!empty($attInfo)){ echo $attInfo[0]['tag2_id'];}?>"/>
             <input type="submit" name="submit" value="Submit" />
        </p>
    </form>
   </div>
</div> 

<script type="text/javascript">

      function validation(){
            var errorCount  = 0;
            var alphaExp    = /^[a-zA-Z\s]+$/;
            var alphaNumExp = /^[a-zA-Z0-9\s]+$/;
            var numExp      = /^[0-9]+$/;

            $('#errors').html('');
            if(($('#tiertag_title').val() == '')){
                errorCount++;
                $('<font color="red" style="font-family: verdana; font-size: 12px;">Attribute Name cannot be blank.</font><br>').appendTo('#errors');
            }
         /*  if(($('#imgfile').val() != '')){
                var rootPath  = '<?php echo $_SERVER['DOCUMENT_ROOT']; ?>'; 
                var fileName  = document.getElementById('imgfile').value;
                var imgPath   = "file:///"+rootPath+"attributeImages/thumb/th_"+ fileName; 
                var extension = fileName.split('.');
                var ext       = extension['1'].toLowerCase();
                if( (ext != 'jpeg') && (ext != 'jpg') && (ext != 'png') && (ext != 'gif') && (ext !='bmp')){
                    errorCount++;
                    $('<font color="red" style="font-family: verdana; font-size: 12px;">Invalid File Format.<br>Please select .jpeg, .jpg, .png, .gif, .bmp file</font><br>').appendTo('#errors');
                }
            }*/
       
            if(errorCount == 0){ 
                return true; //parent.$.fancybox.close();
            }else{
                return false;
            }
    }
</script>