<?php
$loginSession = new Zend_Session_Namespace('login');
$userType = $loginSession->userType;
$tag1List = $this->tag1List;
$tag2List = $this->tag2List;
$tier1List = $this->tier1List; 
$tier2List = $this->tier2List;
$productList = $this->productList;
$productInfo = $this->productInfo;  
$pid = $productInfo['product_id'];
?>
 <script src="/js/jquery-1.8.3.min.js"></script>
 <link rel="stylesheet" type="text/css" href="/js/jcarousels/jcarousel.connected-carousels.css">

<script src="/js/upclick-min.js" type="text/javascript"></script>
<script type="text/javascript">
    $(document).ready(function(){
        
         
        $("#thumbUl li").click(function(){
             $("#thumbUl li").removeClass('active');
             $(this).addClass('active');
        });
        
        
        
        //Add Img <<
        var uploader = document.getElementById('addImgUploder');
        upclick(
        {  //https://code.google.com/p/upload-at-click/
            element: uploader,
            action: '/admin/product-management/product-detail',
            onstart:
                function(filename)
            {
                var file = filename;
                if((file != '')){
                    var extension = file.split('.');
                    var ext       = extension['1'].toLowerCase();
                    if( (ext != 'jpeg') && (ext != 'jpg') && (ext != 'png') && (ext != 'gif') && (ext !='bmp')){
                        alert('Invalid File Format.<br>Please select .jpeg, .jpg, .png, .gif, .bmp file');
                        return false;
                    }else{
                       //alert(file); 
                       $('#hdnProductImg').val(file);
                    }
                }
            },
            oncomplete:
                function(response_data) 
            { //alert(response_data); 
//                if(presetId == 'empty'){
//                   window.location = response_data;
//               }else{
//                   $('#main_image').attr('src', response_data);
//               }
            }
        });
        //Add Img >>
    });
    </script>
<form class="search-add-form" method="post" action="/admin/product-management/product-detail<?php if(!empty($productInfo)){ echo '/pid/'.$pid;}?>" onsubmit="return validation();">
        <p class="title">Search or Add New</p>
        <div class="errors" id="errors"></div>
            <p>
                <select class="styled" name="tier1" id="tier1"><option value="none">Select - Tier1</option>
                <?php
                for ($i = 0; $i < count($tier1List); $i++) {?>
                    <option value="<?php echo $tier1List[$i]['tier1_id']; ?>" <?php if(!empty($productInfo)){ if($productInfo['tier1_id']==$tier1List[$i]['tier1_id']){ echo 'selected=selected';}}?>><?php echo $tier1List[$i]['tier1_name']; ?></option>
                <?php }
                ?>
                </select><span id="eTier1" style="">*</span>
            </p>
            <p>
                <select class="styled" name="tier2" id="tier2"><option value="none">Select - Tier2</option>
                <?php
                for ($i = 0; $i < count($tier2List); $i++) {?>
                    <option value="<?php echo $tier2List[$i]['tier2_id']; ?>" <?php if(!empty($productInfo)){ if($productInfo['tier2_id']==$tier2List[$i]['tier2_id']){ echo 'selected=selected';}}?>><?php echo $tier2List[$i]['tier2_name']; ?></option>
                <?php }
                ?>
                </select><span id="eTier2" style="">*</span>
            </p>
            <p>
                <select class="styled" name="tag1" id="tag1"><option value="none">Select - Tag1</option>
                <?php
                for ($i = 0; $i < count($tag1List); $i++) {?>
                    <option value="<?php echo $tag1List[$i]['tag1_id']; ?>" <?php if(!empty($productInfo)){ if($productInfo['tag1_id']==$tag1List[$i]['tag1_id']){ echo 'selected=selected';}}?>><?php echo $tag1List[$i]['tag1_name']; ?></option>
                <?php }
                ?>
                </select>
            </p>
            <p>
                <select class="styled" name="tag2" id="tag2"><option value="none">Select - Tag2</option>
                <?php
                for ($i = 0; $i < count($tag2List); $i++) {?>
                    <option value="<?php echo $tag2List[$i]['tag2_id']; ?>" <?php if(!empty($productInfo)){ if($productInfo['tag2_id']==$tag2List[$i]['tag2_id']){ echo 'selected=selected';}}?>><?php echo $tag2List[$i]['tag2_name']; ?></option>
                <?php }
                ?>
                </select>
            </p>
            <p>
                <label>Product Name<span id="ePname" style="">*</span></label>
                <input type="text" name="product_name" id="product_name" value="<?php if(!empty($productInfo)){ echo $productInfo['product_name']; }?>"/>
            </p>
            <p>
                <label>Product Number<span id="ePno" style="">*</span></label>
                <input type="text" name="product_number" id="product_number" value="<?php if(!empty($productInfo)){ echo $productInfo['product_num']; }?>"/>
            </p>

            <?php
            if($userType == 'superadmin'){?>
            <p class="price">
                <label>Purchase Price<span id="ePprice" style="">*</span>$</label>
                <input type="text" name="purchase_price" id="purchase_price" value="<?php if(!empty($productInfo)){ echo $productInfo['purchase_price']; }?>"/>
            </p>
            <p class="price">
                <label>Installation Price<span id="eIprice" style="">*</span> $</label>
                <input type="text" name="installation_price" id="installation_price" value="<?php if(!empty($productInfo)){ echo $productInfo['installation_price']; }?>"/>
            </p>
            <p class="price">
                <label>Replacement Cost<span id="eRcost" style="">*</span> $</label>
                <input type="text" name="replacement_price" id="replacement_price" value="<?php if(!empty($productInfo)){ echo $productInfo['replacement_price']; }?>"/>
            </p>
            <p class="price">
                <label>Product Life Span(yrs)<span id="eLspan" style="">*</span></label>
                <input type="text" name="product_life_span" id="product_life_span" value="<?php if(!empty($productInfo)){ echo $productInfo['product_life_span']; }?>"/>
            </p> 
            <?php }else{?>
            <p class="price">
                <label>Cost<span id="ePprice" style="">*</span> $</label>
                <input type="text" name="purchase_price" id="purchase_price" value="<?php if(!empty($productInfo)){ echo $productInfo['purchase_price']; }?>"/>
            </p>    
            <?php 
            }
            ?>
            <p>* Required fields</p>
            <p class="button">
                <a href="/admin/product-management/product-detail"><img src="/images/reset.png" alt="reset" /></a>
                <input type="submit" name="submit" class="save" id="save1" value=""/>
                <input type="button" name="search" class="searchProduct" id="searchProduct" value="Search"/>

                <input type="hidden" id="hdnProductId" name="hdnProductId" value="<?php if(!empty($productInfo)){ echo $productInfo['product_id'];}?>"/>
                <input type="hidden" name="hdnProductImg" id="hdnProductImg" value="<?php if(!empty($productInfo)){ echo $productInfo['product_img'];}?>"/>
    <!--            <a href="#" class="save"><img src="/images/save.png" alt="save" /></a>-->
                <a data-fancybox-type="iframe" href="/admin/product-management/import" class="import"><img src="/images/import-all.png" alt="import all" /></a><br/>
                <a href="/admin/product-management/batch-upload" data-fancybox-type="iframe" class="batchUpload" style="margin-left: 214px;">Batch Upload</a>
            </p>
    </form>
    

    <div class="add-image-slider">




        <div class="connected-carousels">
            <div class="add-image">
                <?php
                if(!empty($pid)){ ?>
                    <a><input type="button" id="addImgUploder" value="Edit Image"/> <span id="eAddImg" style=""><b>*</b></span></a>
                <?php }else{?>
                    <a><input type="button" id="addImgUploder" value="Add Image"/> <span id="eAddImg" style=""><b>*</b></span></a>
                <?php }
                ?>
                
            </div>
              <div class="stage">
                  <div class="carousel carousel-stage">
                      <ul>
                          <li class="li_BigImage">
                              <?php
                              if(!empty($pid)){?>
                                  <img id="bigImg" src="<?php if(!empty($productInfo)){ echo '/batchUpload/main/'.$productInfo['product_img']; }?>" width="520" height="400" alt="">
                              <?php }else{?>
                                  <img id="bigImg" src="/images/product_emptyImag.jpg" width="520" height="400" alt="">
                              <?php }
                              ?>
                              
                          </li>
                      </ul>
                  </div>
<!--                  <a href="#" class="prev prev-stage"><span>&lsaquo;</span></a>
                  <a href="#" class="next next-stage"><span>&rsaquo;</span></a>-->
              </div>
            <!--div class="stage">
                <div class="carousel carousel-stage">
                    <ul>
                        <?php
                        /*if(!empty($productList)){ 
                            foreach ($productList as $key => $value) { ?>
                               <li><img src="/batchUpload/main/<?php echo $value['product_img']?>" width="520" height="400" alt=""></li>
                         <?php  }
                      }else{?>
                             <li><img src="/images/product_emptyImag.jpg" width="520" height="400" alt=""></li>
                        <?php }*/
                        ?>
                        
                    </ul>
                </div>
                <a href="#" class="prev prev-stage"><span>&lsaquo;</span></a>
                <a href="#" class="next next-stage"><span>&rsaquo;</span></a>
            </div-->

            <div class="navigation">
                <a href="#" class="prev prev-navigation">&lsaquo;</a>
                <a href="#" class="next next-navigation">&rsaquo;</a>
                <div class="carousel carousel-navigation">
                    <ul id="thumbUl">
                        <?php
                         if(!empty($productList)){
                             foreach ($productList as $key1 => $value1) { ?>
                                
                             <li id="<?php echo $value1['product_id']; ?>">
                                 <script type="text/javascript">
                                $(document).ready(function(){
                                    $("#<?php echo $value1['product_id']; ?>").click(function(){
                                        $('#bigImg').attr('src','/batchUpload/main/<?php echo $value1['product_img']?>')
                                        
                                        var action = '/admin/product-management/ajax-thumbimag-click/';
                                        var data = 'pid='+<?php echo $value1['product_id']?>;
                                        var response =  getajaxResponse(action,data);
                                        var obj = JSON.parse(response);
                                     
                                        $("#tier1 option[value=" +obj.tier1_id+ "]").attr('selected', 'selected'); 
                                        $("#tier2 option[value=" +obj.tier2_id+ "]").attr('selected', 'selected'); 
                                        $("#tag1 option[value=" +obj.tag1_id+ "]").attr('selected', 'selected'); 
                                        $("#tag2 option[value=" +obj.tag2_id+ "]").attr('selected', 'selected'); 
                                      
                                        $('#product_name').val(obj.product_name);
                                        $('#product_number').val(obj.product_num);
                                        $('#purchase_price').val(obj.purchase_price);
                                        $('#installation_price').val(obj.installation_price);
                                        $('#replacement_price').val(obj.replacement_price);
                                        $('#product_life_span').val(obj.product_life_span);
                                        
                                        $('#hdnProductId').val(obj.product_id);
                                        $('#hdnProductImg').val(obj.product_img);
                                      
                                    });
                                });
                                </script>
                                <img src="/batchUpload/thumb/<?php echo $value1['product_img']?>" width="90" height="90" alt="">
                                <span>
<!--                                    <a href="/admin/product-management/edit-img/pImgId/<?php //echo $value1['product_img']; ?>" data-fancybox-type="iframe" class="batchUpload"><img src="/images/edit-icon.png" alt="edit" /></a>-->
                                     <a href="javascript:void(0);" onclick="editProduct('<?php echo $value1['product_id']; ?>')"><img src="/images/edit-icon.png" alt="edit" /></a>
                                    <a href="javascript:void(0);" onclick="javascript:fnDelProduct('<?php echo $value1['product_id']; ?>','<?php echo $value1['product_img']; ?>')"><img src="/images/delete-icon.png" alt="delete" /></a>
                                </span>
                            </li>
                              <?php  }
                          }else{?>
                             <li>
                                <img src="/images/th_productEmptyImg.jpg" width="90" height="90" alt="">
                             </li>
                         <?php }
                        ?>
                    </ul>
                </div>
            </div>
        </div>
    </div>
     
<script type="text/javascript" src="/js/fancybox/source/jquery.fancybox.js?v=2.1.4"></script>
<link rel="stylesheet" type="text/css" href="/js/fancybox/source/jquery.fancybox.css?v=2.1.4" media="all" />     

<script type="text/javascript" src="/js/jcarousels/jquery.jcarousel.min.js"></script>
<script type="text/javascript" src="/js/jcarousels/jcarousel.connected-carousels.js"></script>
<script type="text/javascript" src="/js/jquery.customSelect.js"></script>
<script type="text/javascript" src="/js/product-detail.js"></script>
<script type="text/javascript">
    function editProduct(productId){ 
        window.location = '/admin/product-management/product-detail/pid/'+productId;
    }    
</script>
