<?php //Path :Default_Collection_collect
$collectionList = $this->collectionList; 
?>
<style>
    .fancybox-wrap{width: 284px !important;}
    .fancybox-skin {
	position: relative;
	padding: 0!important;
	margin: 0;
	background: #f9f9f9;
	color: #444;
	text-shadow: none;
	-webkit-border-radius: 4px;
	   -moz-border-radius: 4px;
	        border-radius: 4px;
                width: 280px !important;
                height: 321px;
}
    .overlay-block input {
        border: 1px solid #8E8D8E;
        border-radius: 5px;
        height: 30px;
        width: 220px;
    }
     .overlay-block {
        -moz-border-bottom-colors: none;
        -moz-border-left-colors: none;
        -moz-border-right-colors: none;
        -moz-border-top-colors: none;
        background: none repeat scroll 0 0 #FFFFFF;
        border-color: #8c8c8c;
        border-image: none;
        border-style: solid none;
        border-width: 40px 0;
/*        display: table;*/
        left: 10px;;
        padding: 10px;
/*        position: fixed;*/
        top: 70px;
        width: 280px;
        height: 322px;
    }
    .overlay-block label {
        font-weight: normal;
        margin: 0 20px 0 0;
        text-align: left;
        width: 220px;
    }
     #btn1{
        background: none repeat scroll 0 0 #8c8c8c;
        border: medium none;
        color: #fff;
        cursor: pointer;
        display: block;
        height: 24px;
        margin: 0 auto;
        font-family: "Gotham SSm A","Gotham SSm B";
        font-size: 13px;
    }
     #btn2{
        background: none repeat scroll 0 0 #8c8c8c;
        border: medium none;
        color: #fff;
        cursor: pointer;
        display: block;
        height: 24px;
        margin: 0 auto;
    }
    .fancybox-item.fancybox-close {
        right: 2px !important;
        top: 2px !important;
    }
    .customSelect styled .customSelectInner{
        width : 205px !important;
    }
    .fancybox-inner{width: 300px !important;}
     .fancybox-outer {height: 321px;width: 100% !important;}
</style>
<link href="/css/frontPanel/bootstrap.min.css" rel="stylesheet">
<link href="/css/frontPanel/style.css" rel="stylesheet">
<link href="/font/font.css" rel="stylesheet">
<script src="/js/jquery-1.8.3.min.js"></script>
<script type="text/javascript" src="/js/fancybox/source/jquery.fancybox.js?v=2.1.4"></script>
<link rel="stylesheet" type="text/css" href="/js/fancybox/source/jquery.fancybox.css?v=2.1.4" media="all" />


<div class='contact-content'>
    
    <form name="frm_collect" id="frm_collect" action="#" method="post"/>
    <div id="collect">
    <div class="overlay-block">
        <div class="errors" id="errors"></div>
        <?php
//            if(!empty($collectionList)){?>
                <p>
                    <label>Save to existing collection:</label>
                    <select name="collectionList" class="styled" id="collectionList" style="border: 1px solid #8E8D8E;border-radius: 5px;height: 30px;width: 220px;padding: 5px 0;">
                        <option value="none"> Select Collection </option>
                        <?php
                        foreach ($collectionList as $key => $value) {?>
                            <option value="<?php echo $value['collection_id'];?>"><?php echo $value['collection_name'];?></option>
                        <?php }
                        ?>
                    </select>
                </p>
                <p>
                    <label style='padding-left:60px;'>OR</label>
                </p>
            <?php
//            }
        ?>
       
        <p>
            <label>Save to new collection:</label>
            <input type="textbox" name="cname" value="" id="cname" class="namec"/>
        </p>        
           
        <p> 
            <input type="hidden" name="hdnProductId" id="hdnProductId" value="<?php if(!empty($_POST['productId'])){ echo $_POST['productId'];} ?>"/>
            <input type="button" name="btn1" id="btn1" value="Save and View Collections" onclick="javascript:click1();"/>
        </p>
        <p>
             <input type="button" name="btn2" id="btn2" value="Save and Return to page" onclick="javascript:click2();"/>
        </p>
    </div>
    </div>
    </form>
</div> 
<!--<script type="text/javascript" src="/js/jquery.customSelect.js"></script>-->
<script  type="text/javascript">
//    $().ready(function(){
//        $('select.styled').customSelect();
//    });
    /*function isValidCollection(){
        var errorCount  = 0;
        var alphaExp    = /^[a-zA-Z\s]+$/;
        var alphaNumExp = /^[a-zA-Z0-9\s]+$/;
        var numExp      = /^[0-9]+$/; 
        
        $('#errors').html('');
        if(  ($('#collectionList').val() == 'none') && ($('#cname').val() == '') ) {
            errorCount++;
            $('<font color="red" style="font-family: verdana; font-size: 12px;">Both option can not blank</font><br>').appendTo('#errors');
        }
        if(  ($('#collectionList').val() != 'none') && ($('#cname').val() != '') ) {
            errorCount++;
            $('<font color="red" style="font-family: verdana; font-size: 12px;">Select only one section</font><br>').appendTo('#errors');
        }

        if(errorCount == 0){
            return true;
        }else{
            return false;
        }
    }*/
    function click1(){
        var errorCount  = 0;
        var alphaExp    = /^[a-zA-Z\s]+$/;
        var alphaNumExp = /^[a-zA-Z0-9\s]+$/;
        var numExp      = /^[0-9]+$/; 
        
       // alert( $('#collectionList').val()+'---'+$('#cname').val()); return false;
        $('#errors').html('');
        if(  ($('#collectionList').val() == 'none') && ($('#cname').val() == '') ) {
            errorCount++;
            $('<font color="red" style="font-family: verdana; font-size: 12px;">Both option can not blank</font><br>').appendTo('#errors');
        }
        if(  ($('#collectionList').val() != 'none') &&  $('#collectionList').val() != undefined && ($('#cname').val() != '') ) {
            errorCount++;
            $('<font color="red" style="font-family: verdana; font-size: 12px;">Select only one section</font><br>').appendTo('#errors');
        }
        if( $('#collectionList').val() == undefined && ($('#cname').val() == '')){
            errorCount++;
            $('<font color="red" style="font-family: verdana; font-size: 12px;">Collection Name is required.</font><br>').appendTo('#errors');
        }
            
        

        if(errorCount == 0){
                var cId = $('#collectionList').val();  
                if($('.namec').val() != ''){
                    var cname   = $('.namec').val() ;
                }else{
                    var cname = 'none';
                }
                var productId    =  "<?php echo $_POST['productId'] ?>";
           
             
                $.ajax({
                    type: "GET",
                    url: "/collection/collectadd",
                    data : { productId : productId , cId : cId, cname : cname },
                        success: function(data) { 
                        if (data == 'success') {
                            location.href = '/collection';
                            parent.jQuery.fancybox.close();
                        }
                    },
                    error: function(event, request, settings) {
                        return false;
                    }
                });
            } else {
                return false;
            }
        }
        function click2(){
            var errorCount  = 0;
            var alphaExp    = /^[a-zA-Z\s]+$/;
            var alphaNumExp = /^[a-zA-Z0-9\s]+$/;
            var numExp      = /^[0-9]+$/; 

            $('#errors').html('');
            if(  ($('#collectionList').val() == 'none') && ($('#cname').val() == '') ) {
                errorCount++;
                $('<font color="red" style="font-family: verdana; font-size: 12px;">Both option can not blank</font><br>').appendTo('#errors');
            }
            if(  ($('#collectionList').val() != 'none') &&  $('#collectionList').val() != undefined && ($('#cname').val() != '') ) {
            errorCount++;
            $('<font color="red" style="font-family: verdana; font-size: 12px;">Select only one section</font><br>').appendTo('#errors');
            }
            if( $('#collectionList').val() == undefined && ($('#cname').val() == '')){
                errorCount++;
                $('<font color="red" style="font-family: verdana; font-size: 12px;">Collection Name is required.</font><br>').appendTo('#errors');
            }

            if(errorCount == 0){
                var cId = $('#collectionList').val();  
                if($('.namec').val() != ''){
                    var cname   = $('.namec').val() ;
                }else{
                    var cname = 'none';
                }
                var productId    =  "<?php echo $_POST['productId'] ?>";
                $.ajax({
                    type: "GET",
                    url: "/collection/collectadd",
                    data : { productId : productId , cId : cId, cname : cname },
                    success: function(data) { //alert(data); return false;
                        if (data == 'success') {
                            location.reload();
                            parent.jQuery.fancybox.close();
                        }
                    },
                    error: function(event, request, settings) {
                        return false;
                    }
                });
            } else {
                return false;
            }
        }
</script>