<?php
$loginSession = new Zend_Session_Namespace("login");
$errorMsg = $this->errorMessage;
?>
<!DOCTYPE html>
<html>
    <head>
          <title>MGP - <?php echo APP_TITLE; ?> | Admin</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no">
        <!-- Bootstrap -->
        <link href="/css/bootstrap.min.css" rel="stylesheet">
        <link href="/css/style.css" rel="stylesheet">
        <link href="/font/font.css" rel="stylesheet">
        <style>
            .login-block form {
                display: table;
                margin: 40px auto;
                width: 200px;
            }
            .login-block label {
                color: #4D4D4D;
                font-family: "PT Sans";
                font-size: 16px;
                font-weight: normal;
                width: 100%;
            }
            label {
                display: inline-block;
                margin-bottom: 5px;
                font-weight:normal;
            }
            .login-block a {
                color: #4D4D4D;
                font-family: "PT Sans";
                font-size: 15px;
            } 
        </style>
        <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
          <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
          <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
        <![endif]-->
        <script src="/js/jquery-1.8.3.min.js"></script>
    </head>
    <body>
        <div class="wrapper">
            <div class="row header">
                <div class="container">
                    <div class="col-md-6" style="padding-left: 220px;width: 790px;">
                        <!--<a href="#" class="logo"><img src="/images/toto-logo.png" alt="toto" class="img-responsive" /></a>-->
                        <a href="#" class="logo"><img src="/images/frontPanel/mgp-logo.png" alt="toto" class="img-responsive" /></a>
                        <span class="separator">-</span>
                        <span class="admin-text" style="color: #4D4D4D;"><?php echo APP_TITLE; ?></span>
                        <span class="separator">|</span>
                        <span class="admin-text">Admin</span>
                        
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="container content">


                    <div class="login-block" style="height: 363px;">
                        <form id="frmLogin" action="/admin/index" method="post">
                            <?php if ($errorMsg != "")
                                echo "<div style='color:red';>" . $errorMsg . "</div>"; ?><br/>
                            <p>
                                <label>Email:</label> 
                                <input type="text" name="txtusername" id="txtusername" style="border: 1px solid #B3B3B3;height: 25px;width: 100%;" />
                            </p>
                            <p>
                                <label>Password:</label> 
                                <input type="password" name="txtpassword" id ="txtpassword" style="border: 1px solid #B3B3B3;height: 25px;width: 100%;" />
                            </p>
                            <br/><a class="login-btn"><input type="image" src="/images/login-button.jpg" name="btnSumbit" value="" onclick="return validateUser();" /></a>
                        </form>
                    </div>
                </div><!-- container content end-->
            </div><!-- row end -->
        </div><!-- wrapper end -->

    </body>
</html>