<link href="/css/bootstrap.min.css" rel="stylesheet">
<link href="/css/style.css" rel="stylesheet">
<link href="/font/font.css" rel="stylesheet">
<style>
    .overlay-block input {
        border: 1px solid #8E8D8E;
        border-radius: 5px;
        height: 30px;
        width: 200px;
    }
    .overlay-block {
        -moz-border-bottom-colors: none;
        -moz-border-left-colors: none;
        -moz-border-right-colors: none;
        -moz-border-top-colors: none;
        background: none repeat scroll 0 0 #FFFFFF;
        border-color: #8CC63F -moz-use-text-color;
        border-image: none;
        border-style: solid none;
        border-width: 40px 0;
/*        display: table;*/
        left: 0px;;
        padding: 20px;
        position: fixed;
        top: 0px;
        width: 444px;
        height: 321px;
    }
      .overlay-block label {
        font-weight: normal;
        margin: 0 20px 0 0;
        text-align: left;
        width: 121px;
    }
    #submit{
        background:url(/images/save.png) no-repeat top left;
        width:60px;
        height:28px;
        border:none;
        cursor:pointer;
    }
    .errors {
    color: #FF0000;
}
#attribute{
    border: 1px solid #8E8D8E;
    border-radius: 5px;
    padding: 4px 5px;
    width: 200px;
}
</style>
<?php
$attList = $this->attList; 
$subAttInfo = $this->subAttInfo; 
?>

<script src="/js/jquery-1.8.3.min.js"></script>
<script type="text/javascript" src="/js/fancybox/source/jquery.fancybox.js?v=2.1.4"></script>
<link rel="stylesheet" type="text/css" href="/js/fancybox/source/jquery.fancybox.css?v=2.1.4" media="all" />
<?php
    if(!empty($this->succMesg)){?>
    <script language="JavaScript" type="text/javascript">
    $(document).ready(function() { 
        parent.jQuery.fancybox.close();
    });
    </script>
    <?php }
?>
<div class='contact-content'><div class="overlay-block"><div class="errors" id="errors"></div><br/>
<form id="addSubAttForm" action="/admin/attribute-management/subatt/<?php if(!empty($subAttInfo)){ echo '/id/'.$subAttInfo['subatt_id']; }?>" method="post" onsubmit="return validation();">
    <p>
        <label>Attribute</label>
        <select name="attribute" id="attribute">
            <option value="Select">Select</option>
            <?php
            for ($i = 0; $i < count($attList); $i++) {?>
                <option value="<?php echo $attList[$i]['attribute_id']; ?>" <?php if(!empty($subAttInfo)){ if($subAttInfo['attribute_id']==$attList[$i]['attribute_id']){ echo 'selected=selected';}}?>><?php echo $attList[$i]['attribute_name']; ?></option>
            <?php }
            ?>
        </select>
    </p>
    <p>
        <label>Sub-Attribute Name</label>
        <input type="text" name="subattName" id="subattName" value="<?php if(!empty($subAttInfo)){ echo $subAttInfo['subatt_name'];}?>" style='padding-left:3px;'/>
    </p>
    <p>
         <input type="hidden" name="hdnSunattId" value="<?php if(!empty($subAttInfo)){ echo $subAttInfo['subatt_id'];}?>"/>
         <input type="submit" name="submit" value="" id="submit" />
    </p>
</form>
</div>
<script type="text/javascript">
    function validation(){
        var errorCount  = 0;
        var alphaExp    = /^[a-zA-Z\s]+$/;
        var alphaNumExp = /^[a-zA-Z0-9\s]+$/;
        var numExp      = /^[0-9]+$/;
        
        $('#errors').html('');
        if(($('#attribute').val() == 'Select')){
            errorCount++;
            $('<font>Please Select Attribute option.</font><br>').appendTo('#errors');
        }
        if(($('#subattName').val() == '')){
            errorCount++;
            $('<font>Sub-Attribute Name cannot be blank.</font><br>').appendTo('#errors');
        }
        
        if(errorCount == 0){
            return true;
        }else{
            return false;
        }
    }
</script>