

<div class='contact-content'>
    <div id="collect">
    <div class="overlay-block">
        
<div id="emailError" name="emailError" class="errorText" style="text-align:center;"></div>
<div id="passerrors" name="passerrors"  style="color:red;text-align:center;"></div>
<div id="loading" style="display:none;text-align:center;margin-top:30px;"><img src="/images/loader.gif" ><br>Please Wait...</div>
<div id="successMsg" style="display:none;text-align:center;color:green;margin-top:30px;">...</div>
<!--    <form method="post"  name="changePwdForm" id="changePwdForm">-->
        <table border="0" cellspacing="0" cellpadding="0" align="center" width="100%" style="">
            <tr><td>&nbsp;</td></tr>
            <tr>
                <td align="left">Old Password:<span class="reqdfield">*</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input type="password" id="pwdOldPwd" name="pwdOldPwd" class="text ui-widget-content ui-corner-all" value=""></td>
            </tr>
            <tr><td>&nbsp;</td></tr>
            <tr>
                <td align="left">New Password:<span class="reqdfield">*</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input type="password" id="pwdNewPwd" name="pwdNewPwd"  class="text ui-widget-content ui-corner-all"></td>
            </tr>
            <tr><td>&nbsp;</td></tr>
            <tr>
                <td align="left">Confirm Password:<span class="reqdfield">*</span>&nbsp;&nbsp;<input type="password" id="pwdConfirmPwd" name="pwdConfirmPwd" class="text ui-widget-content ui-corner-all"></td>
            </tr>
        </table>
<div style="display: table;
    margin: 20px auto;
    width: auto;">
    <a  href="javascript:void(0);" onclick="javascript:changePasswordNew();" class="pswdContinue" id="resetpsdButtons" style="">Continue</a>
             <a class="pswdCancel"  style="display:none;" id="resetpsdButtons" style="">Cancel</a>
</div>
        <input type="hidden" name="hidAction" id="hidAction" value="changePwd">
<!--    </form>-->
        </div>
        </div>
</div>
<link href="/css/frontPanel/bootstrap.min.css" rel="stylesheet">
<link href="/css/frontPanel/style.css" rel="stylesheet">
<link href="/font/font.css" rel="stylesheet">
<script src="/js/jquery-1.8.3.min.js"></script>
<script type="text/javascript" src="/js/resetPwd.js"></script>
     
<style>
    
    .overlay-block input {
        border: 1px solid #8c8c8c;
        border-radius: 5px;
        height: 30px;
        width: 100%;
    }
     .overlay-block {
        -moz-border-bottom-colors: none;
        -moz-border-left-colors: none;
        -moz-border-right-colors: none;
        -moz-border-top-colors: none;
        background: none repeat scroll 0 0 #FFFFFF;
        border-color: #8c8c8c;
        border-image: none;
        border-style: solid none;
        border-width: 40px 0;
        left: 10px;;
        padding: 10px;
        top: 70px;
    }
    .overlay-block label {
        font-weight: normal;
        margin: 0 20px 0 0;
        text-align: left;
        width: 220px;
    }

    #resetpsdButtons{
        cursor: pointer;
       background: none repeat scroll 0% 0% rgb(140, 140, 140); border-radius: 5px; text-decoration: none; color: rgb(255, 255, 255); padding: 5px 8px; 
    }
</style>