<!DOCTYPE html>
<html>
    <head>
        <title>MGP - <?php echo APP_TITLE; ?> | Admin</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no">
        <!-- Bootstrap -->
        <link href="/css/bootstrap.min.css" rel="stylesheet">
        <link href="/css/style.css" rel="stylesheet">
        <link href="/font/font.css" rel="stylesheet">
        <link rel="stylesheet" type="text/css" href="//cloud.typography.com/7172712/723186/css/fonts.css" />

        <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
          <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
          <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
        <![endif]-->
        <script src="/js/jquery-1.8.3.min.js"></script>
        <script id="loader" src="/js/loaderscript.js" type="text/javascript"></script>
        
        <!-- Google Analytic << -->
     <script>
            (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
            (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
            m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
            })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

            ga('create', 'UA-56826391-1', 'auto');
            ga('send', 'pageview');

      </script>
        <!-- Google Analytic >> -->
        
    </head>
    <body><div class="ajax_loader"></div>
        <div class="wrapper">
            <div class="row header">
                <?php echo $this->partial("admin-header.phtml"); ?>
            </div>
            <div class="row">
                <?php 
                    $query1 = explode("/", $_SERVER['REQUEST_URI']); 
                    if (in_array("attribute-management", $query1)) { $divClass = 'container content attribute';}
                    if (in_array("product-detail", $query1)) { $divClass = 'container content product-details';}
                    if (in_array("category-setup", $query1)) { $divClass = 'container content';}
                    if (in_array("landing-page", $query1)) { $divClass = 'container content';}
                    if (in_array("mastergrid", $query1)) { $divClass = 'container content';}
                    if (in_array("user-management", $query1)) { $divClass = 'container content user-management-block';}
                    if (in_array("import-management", $query1)) { $divClass = 'container content product-details';}
                    
                ?>
                <div class="<?php echo $divClass; ?>">
                    <div class="navigation">
                         <?php echo $this->partial("admin-navigation.phtml"); ?>
                    </div>
                    <?php echo $this->layout()->content; ?>
                </div><!-- container content end-->
            </div><!-- row end -->
        </div><!-- wrapper end -->
        <script type="text/javascript">
            $().ready(function(){
                $(".ajax_loader").hide();
            });
        </script>
        <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
        <!--<script src="https://code.jquery.com/jquery.js"></script>-->
        <!-- Include all compiled plugins (below), or include individual files as needed -->
        <script src="/js/bootstrap.min.js"></script>
        <link rel="stylesheet" href="/js/checkbox/dist/prettyCheckable.css">
        <script src="/js/checkbox/dev/prettyCheckable.js"></script>
        <script src="/js/script.js"></script>
        <script src="/js/common.js"></script>  
       
     </body>
</html>
