<!--<div class="row gray-bg" >
    <div class="container">
        <div class="col-md-4 col-sm-4 col-xs-12 address-block">
            <h2>COMPANY INFO</h2>
            <div class="address">
                <img src="/images/frontPanel/phone.png" alt="atlanta" class="img-responsive map" />
                <div class="address-text">
                    <p>239-633-6508</p>
                </div>
            </div>
            <div class="address">
                <img src="/images/frontPanel/email.png" alt="bogota" class="img-responsive map" />
                <div class="address-text">
                    <p><a href="mailto:info@mygreenpayback.com">info@mygreenpayback.com</a></p>
                </div>
            </div>
        </div>
        <div class="col-md-4 col-sm-4 col-xs-12 contact-us">
            <h2>CONTACT US</h2>
            <div class="address">
                <a target="_blank" href="https://www.facebook.com/mygreenpayback"><img src="/images/frontPanel/footer-facebook.png" alt="facebook" class="img-responsive map" /> LIKE</a>
            </div>
            <div class="address">
                <a target="_blank" href="https://twitter.com/mygreenpayback"><img src="/images/frontPanel/footer-twitter.png" alt="twitter" class="img-responsive map" />FOLLOW</a>
            </div>
            <div class="address">
                <a target="_blank" href="#"><img src="/images/frontPanel/footer-linkedin.png" alt="linkedin" class="img-responsive map" />CONNECT</a>
            </div>
        </div>
        <div class="col-md-4 col-sm-4 col-xs-12">
            <h2>SEND US A MESSAGE</h2>
            <div class="address">
                <a href="mailto:info@mygreenpayback.com" class="click-here"><img src="/images/frontPanel/footer-click-here.png" alt="facebook" class="img-responsive" /></a>
            </div>
        </div>
    </div>
</div>-->
<div class="row green">
    <div class="container">
        <p>Powered by: <a href="http://www.mygreenpayback.com" style="color:#8cc63f;">MyGreenPayback</a> &copy All Rights Reserved</p>
    </div>
</div>